spring:
  application:
    name: identity-service
  profiles:
    active: dev
  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
    com.zwind.grpc_security_starter: DEBUG
